GET http://localhost:8000/api/v1/jobs

###
GET http://localhost:8000/api/v1/jobs/64d3f456827c5826f6c65c8a

###
###
DELETE  http://localhost:8000/api/v1/jobs/64d3f2fe827c5826f6c65c80

###

POST http://localhost:8000/api/v1/jobs
Content-Type: application/json

{
    "title": "New Job 2 update option",
    "description": "Description for the new job",
    "budget": 1200,
    "skills" : ["Project Management", "Ms Word"],
    "schedule": "3 days"
}
###

POST  http://localhost:8000/api/v1/jobs
Content-Type: application/json

{
    "title": "New Job 2 New Usiku 2",
    "description": "Description for the new job",
    "budget": 1200,
    "skills" : ["Project Management", "Ms Word"],
    "schedule": "3 days"
}
###

PUT http://localhost:8000/api/v1/jobs/64d3f456827c5826f6c65c8a
Content-Type: application/json

{
    "title": "New Job 2023 New Usiku Updated",
    "description": "",
    "budget": 1200,
    "skills" : ["Project Management", "Ms Word"],
    "schedule": "65 days"
}