GET http://localhost:8000/api/v1/jobs

###
POST http://localhost:8000/api/v1/jobs 
Content-Type: application/json

{
    "title" : "New Job",
    "description": "New Job Description",
    "schedule" : "1 week",
    "buget" : 200
}