
###
GET http://localhost:8000/api/v1/users

###
GET http://localhost:8000/api/v1/profile/

###
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "assist.africa1@gmail.com",
    "password": "12345678" 
}


###
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "role": "Freelancer",
    "type" : "Individual",
    "name": "George Oloo",
    "email": "collog1824@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:8000/api/v1/logout

###

GET http://localhost:8000/api/v1/profile/

###
PATCH  http://localhost:8000/api/v1/profile/
Content-Type: application/json

{
    "name": "",
    "email": "",
    "phone": "",
    "location" : "",
    "experience" :"",
    "skills" : [],
    "schedule" : "",
    "tasks" : "",
    "hours" : "",
    "portfolio" : "",
    "sample_work" : "",
    "payment_method" : "",
    "payment_rate" : ""
}