GET http://localhost:8000/api/v1/profile/64d26e68c917260a5a69f795

###

GET http://localhost:8000/api/v1/profile

###
GET http://localhost:8000/api/v1/profile/64d3ffd7330af79ed8595e48

###

POST http://localhost:8000/api/v1/profile/64d26e68c917260a5a69f795
Content-Type: application/json

{
"phone": 2354678755,
"location": "Nairobi 2"
}
###

POST http://localhost:8000/api/v1/profile/64d26060a21768aab4b9a1bd
Content-Type: application/json

{
"phone": 2354678755,
"location": "Eldoret Annex"
}