
###
GET http://localhost:8000/api/v1/users

###
GET http://localhost:8000/api/v1/profile/

###
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "assist.africa1@gmail.com",
    "password": "12345678" 
}


###
POST http://localhost:8000/api/v1/register/client
Content-Type: application/json

{
    "type" : "Individual",
    "name": "Assist Africa 13",
    "email": "assist.africa13@gmail.com",
    "password": "Olosko2018?",
    "consultation": "true"
}

###
POST http://localhost:8000/api/v1/register/freelancer
Content-Type: application/json

{
    "type" : "Individual",
    "name": "Assist Africa 12",
    "email": "assist.africa12@gmail.com",
    "password": "Olosko2018?"
}

###
POST http://localhost:8000/api/v1/logout

###

GET http://localhost:8000/api/v1/users/

###
PATCH  http://localhost:8000/api/v1/profile/
Content-Type: application/json

{
    "name": "",
    "email": "",
    "phone": "",
    "location" : "",
    "experience" :"",
    "skills" : [],
    "schedule" : "",
    "tasks" : "",
    "hours" : "",
    "portfolio" : "",
    "sample_work" : "",
    "payment_method" : "",
    "payment_rate" : ""
}